### ISSUE TITLE
图片显示

### ISSUE THREAD

**Issue by 7117** [wsy555/wangsy.github.io#5]
源代码很好，质量很高，谢谢您的开源；
我遇到的问题，图片显示不出，步骤：
1.控制器www里面修改图片的地址至静态图片地址
2.修改视图里https至http ,www.kaixin00.com至127.0.0.1:8081

PPGo_ApiAdmin的项目名字
在项目里面搜索下PPGo_ApiAdmin全修改成gushici就可以。

**Comment by wsy555** [comment]
图片就用相对路径，，没有问题呀，我是view模板写了绝对路径：style="background: url(http://www.kaixin00.com{{$elem.picurl}}{{.webp}})，修改成你的地址，或者去掉

**Comment by 7117** [comment]
好的，三克油~
